package com.womai.platform.dao.mapper;

import com.womai.platform.dao.model.Accounts;

import java.util.HashMap;
import java.util.List;

public interface AccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int insert(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int insertSelective(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    Accounts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accounts record);

    List<Accounts> selectList();

    List<Integer> selectIds();

    List<Accounts> selectListByPage(HashMap<String, Integer> offsetLimit);

    int getCount();
}